image: maven:latest

before_script:
  - chmod +x mvnw

stages:
  - staging
      
staging:
  stage: staging
  image: alpine:latest
  script: 
      - apk upgrade
      - apk add ruby-dev
      - apk add openjdk11
      - gem install dpl
      - ./mvnw install
  artifacts:
    paths:
      - target/eureka-0.0.1-SNAPSHOT.jar
  only:
      - master