image: maven:latest

before_script:
  - chmod +x mvnw

stages:
  - installation
  - staging
  
installation:
  stage: installation
  script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - apt-get update -qy
      - apt-get install -y python-dev python-pip
      - gem install dpl
      
staging:
  stage: staging
  image: openjdk:latest
  script: 
      - ./mvnw install
      - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  artifacts:
    paths:
      - target/eureka-0.0.1-SNAPSHOT.jar
  only:
      - master