image: maven:latest

before_script:
  - chmod +x mvnw

stages:
  - staging

staging:
  type: deploy
  stage: staging
  image: ubuntu:latest
  script: 
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
      - dpl --provider=heroku --app=./target/eureka-0.0.1-SNAPSHOT.jar --api-key=42b3fe32-89db-499d-a5eb-efea04adc79c
  artifacts:
    paths:
      - target/eureka-0.0.1-SNAPSHOT.jar
  only:
      - master