image: openjdk:latest

before_script:
  - apt-get update -qy
  - chmod +x mvnw
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
- staging

build:
  stage: staging
  image: openjdk:latest 
  script: 
      - ./mvnw install
      - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  artifacts:
    paths:
      - target/eureka-0.0.1-SNAPSHOT.jar
  only:
      - master