image: maven:latest

before_script:
  - chmod +x mvnw

stages:
  - staging
      
staging:
  stage: staging
  image: openjdk:latest && alpine:latest
  script: 
      - apk upgrade
      - apk add ruby-dev
      - gem install dpl
      - ./mvnw install
      - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  artifacts:
    paths:
      - target/eureka-0.0.1-SNAPSHOT.jar
  only:
      - master