image: maven:latest

before_script:
  - chmod +x mvnw

stages:
  - build
  - deploy

build:
  stage: build
  image: ubuntu:latest
  script: 
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
      - apt-get install -y default-jdk
      - ./mvnw install
      - pwd
  artifacts:
    paths:
      - target/
  only:
      - master
      
deploy_staging:
  stage: build
  image: openjdk:latest
  script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
      - ./mvnw install
      - dpl --provider=heroku --app=${HEROKU_APP_STAGING} --api-key=${HEROKU_API_KEY}
  only:
      - master