image: java:latest

before_script:
- chmod +x mvnw

stages:
- staging

build:
  stage: staging
  script: 
      - ./mvnw install
      - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  artifacts:
    paths:
      - /builds/diego.alura/timesheet-io-eureka/target/eureka-0.0.1-SNAPSHOT.jar
  only:
      - master