mage: java:latest

before_script:
- chmod +x mvnw

stages:
- staging

staging:
  stage: build
  script:
  - ./mvnw package
  artifacts:
    paths:
    - target/eureka-0.0.1-SNAPSHOT.jar
  only:
  - master