image: openjdk:latest

before_script:
- chmod +x mvnw

stages:
- staging

build:
  stage: staging
  script: 
      - ./mvnw install
  artifacts:
    paths:
      - target/eureka-0.0.1-SNAPSHOT.jar
  only:
      - master